### ISSUE TITLE
"invalid remote port" when data starts flowing

### ISSUE THREAD

**Issue by potmat** [shinyoshiaki/werift-webrtc#142]
The following offer:

```
v=0
o=- 25373548 0 IN IP4 0.0.0.0
s=-
t=0 0
a=group:BUNDLE 0 1 2
a=extmap-allow-mixed
a=msid-semantic:WMS *
m=audio 9 UDP/TLS/RTP/SAVPF 96
c=IN IP4 0.0.0.0
a=ice-ufrag:e1e6
a=ice-pwd:3de05c27f761027baaeda2
a=ice-options:trickle
a=fingerprint:sha-256 02:35:32:AF:E1:44:8A:91:D3:54:BB:14:8C:40:2A:73:0A:81:57:14:E8:1D:4B:0E:C4:A2:D6:68:D4:5D:1E:6A
a=setup:actpass
a=recvonly
a=mid:0
a=msid:3a3e0c15-b3e6-4f46-bf38-bd904b44b782 c5af7974-995a-4a06-af72-84d0e2a69295
a=rtcp:9 IN IP4 0.0.0.0
a=rtcp-mux
a=ssrc:2112560515 cname:58cdd469-29cc-4620-bbfa-1e44461d2c76
a=rtpmap:96 opus/48000/2
m=video 9 UDP/TLS/RTP/SAVPF 97
c=IN IP4 0.0.0.0
a=ice-ufrag:e1e6
a=ice-pwd:3de05c27f761027baaeda2
a=ice-options:trickle
a=fingerprint:sha-256 02:35:32:AF:E1:44:8A:91:D3:54:BB:14:8C:40:2A:73:0A:81:57:14:E8:1D:4B:0E:C4:A2:D6:68:D4:5D:1E:6A
a=setup:actpass
a=recvonly
a=mid:1
a=msid:92de723a-910d-47b8-a694-ba16846c2155 7b970e2e-6610-42c4-9c0a-973953222f42
a=rtcp:9 IN IP4 0.0.0.0
a=rtcp-mux
a=ssrc:321650976 cname:58cdd469-29cc-4620-bbfa-1e44461d2c76
a=rtpmap:97 VP8/90000
a=rtcp-fb:97 ccm fir
a=rtcp-fb:97 nack
a=rtcp-fb:97 nack pli
a=rtcp-fb:97 goog-remb
m=application 9 UDP/DTLS/SCTP webrtc-datachannel
c=IN IP4 0.0.0.0
a=ice-ufrag:e1e6
a=ice-pwd:3de05c27f761027baaeda2
a=ice-options:trickle
a=fingerprint:sha-256 02:35:32:AF:E1:44:8A:91:D3:54:BB:14:8C:40:2A:73:0A:81:57:14:E8:1D:4B:0E:C4:A2:D6:68:D4:5D:1E:6A
a=setup:actpass
a=mid:2
a=sctp-port:5000
a=max-message-size:65536
```

and answer:

```
v=0
o=- 0 2 IN IP4 127.0.0.1
s=-
t=0 0
a=group:BUNDLE 0 2 1
a=msid-semantic: WMS 13945094204333313074/3212739396 virtual-6666
a=ice-lite
m=audio 19305 UDP/TLS/RTP/SAVPF 96
c=IN IP4 <redacted>
a=rtcp:9 IN IP4 0.0.0.0
a=candidate: 1 udp 2113939711 2607:f8b0:400e:c03::7f 19305 typ host generation 0
a=candidate: 1 tcp 2113939710 2607:f8b0:400e:c03::7f 19305 typ host tcptype passive generation 0
a=candidate: 1 ssltcp 2113939709 2607:f8b0:400e:c03::7f 443 typ host generation 0
a=candidate: 1 udp 2113932031 74.125.197.127 19305 typ host generation 0
a=candidate: 1 tcp 2113932030 74.125.197.127 19305 typ host tcptype passive generation 0
a=candidate: 1 ssltcp 2113932029 74.125.197.127 443 typ host generation 0
a=ice-ufrag:KFPTBCP4YKPZTY1Q
a=ice-pwd:VA0L9MQMWS8IYO9NJF+ITE++
a=fingerprint:sha-256 92:D6:06:D6:CB:64:B4:EF:47:76:00:F7:48:E0:ED:DD:9F:3E:DA:16:41:49:47:43:E0:77:DD:C6:D7:83:7E:19
a=setup:passive
a=mid:0
a=sendrecv
a=msid:virtual-6666 virtual-6666
a=rtcp-mux
a=rtpmap:96 opus/48000/2
a=fmtp:96 minptime=10;useinbandfec=1
a=ssrc:6666 cname:6666
m=video 9 UDP/TLS/RTP/SAVPF 97
c=IN IP4 0.0.0.0
a=rtcp:9 IN IP4 0.0.0.0
a=ice-ufrag:KFPTBCP4YKPZTY1Q
a=ice-pwd:VA0L9MQMWS8IYO9NJF+ITE++
a=fingerprint:sha-256 92:D6:06:D6:CB:64:B4:EF:47:76:00:F7:48:E0:ED:DD:9F:3E:DA:16:41:49:47:43:E0:77:DD:C6:D7:83:7E:19
a=setup:passive
a=mid:1
a=sendrecv
a=msid:13945094204333313074/3212739396 13945094204333313074/3212739396
a=rtcp-mux
a=rtpmap:97 VP8/90000
a=rtcp-fb:97 ccm fir
a=rtcp-fb:97 nack
a=rtcp-fb:97 nack pli
a=rtcp-fb:97 goog-remb
a=ssrc:3212739396 cname:3212739396
m=application 9 DTLS/SCTP 5000
c=IN IP4 0.0.0.0
a=ice-ufrag:KFPTBCP4YKPZTY1Q
a=ice-pwd:VA0L9MQMWS8IYO9NJF+ITE++
a=fingerprint:sha-256 92:D6:06:D6:CB:64:B4:EF:47:76:00:F7:48:E0:ED:DD:9F:3E:DA:16:41:49:47:43:E0:77:DD:C6:D7:83:7E:19
a=setup:passive
a=mid:2
a=sctpmap:5000 webrtc-datachannel 1024
```

At the start of data flow an ack will try to be sent and the remote port of the server will be undefined here: https://github.com/shinyoshiaki/werift-webrtc/blob/develop/packages/sctp/src/sctp.ts#L1111

Probably related to: https://github.com/shinyoshiaki/werift-webrtc/issues/141, to make this work I had to "hack" the answer sdp to change "sctpmap" to "sctpMap".

**Comment by shinyoshiaki** [comment]
The cause seems to be that "a=sctp-port" is not included in the SDP of answer.

I think this problem can be fixed by getting the sctpPort from "a=sctpmap" when there is no ""a=sctp-port"".

Which WebRTC engine do you use for the answer side? I want to debug if the problem can be fixed with this solution.

**Comment by potmat** [comment]
Hi @shinyoshiaki, the answer is actually from an external API: https://developers.google.com/nest/device-access/traits/device/camera-live-stream#generatewebrtcstream

As such, I don't think there's any way for you to debug it.  If it would help you can create a branch and I can try running against that branch to test any possible solutions.

**Comment by shinyoshiaki** [comment]
Try it on this branch
https://github.com/shinyoshiaki/werift-webrtc/tree/maintain/issue141-142

**Comment by potmat** [comment]
Hi @shinyoshiaki, wow thank you so much.  Forgive my inexperience with NPM but how do I reference this branch in my code?  It does not appear to be "built"?  That is, the package.json has no "main" entry, and there are no .js files?  Having this in my package.json:

`"werift": "github:shinyoshiaki/werift-webrtc#maintain/issue141-142"`

Does not work. Do I need to fork the repo and run some build scripts?

**Comment by shinyoshiaki** [comment]
This repository uses a mono repo, so you can't do npm install by referencing the github branch.
We have released a test version, so please use this.
`"werift": "debug"`

**Comment by potmat** [comment]
Hi @shinyoshiaki, using

`"werift": "debug"`

Does not seem to resolve either issue.  Is still expecting "sctpMap" and hacking the answer to change it will still result in:

```
/Users/me/Source/webrtctest/node_modules/werift/lib/sctp/src/sctp.js:888
            throw new Error("invalid remote port");
                  ^

Error: invalid remote port
    at SCTP.sendChunk (/Users/me/Source/webrtctest/node_modules/werift/lib/sctp/src/sctp.js:888:19)
    at SCTP.receiveChunk (/Users/me/Source/webrtctest/node_modules/werift/lib/sctp/src/sctp.js:290:32)
    at SCTP.handleData (/Users/me/Source/webrtctest/node_modules/werift/lib/sctp/src/sctp.js:231:24)
    at RTCDtlsTransport.SCTP.transport.onData [as dataReceiver] (/Users/me/Source/webrtctest/node_modules/werift/lib/sctp/src/sctp.js:196:18)
    at Object.execute (/Users/me/Source/webrtctest/node_modules/werift/lib/webrtc/src/transport/dtls.js:89:22)
    at Event.execute (/Users/me/Source/webrtctest/node_modules/rx.mini/lib/core/index.js:17:30)
    at IceTransport.DtlsSocket.udpOnMessage [as onData] (/Users/me/Source/webrtctest/node_modules/werift/lib/dtls/src/socket.js:70:45)
    at Object.execute (/Users/me/Source/webrtctest/node_modules/werift/lib/webrtc/src/transport/dtls.js:221:26)
    at Event.execute (/Users/me/Source/webrtctest/node_modules/rx.mini/lib/core/index.js:17:30)
    at Connection.dataReceived (/Users/me/Source/webrtctest/node_modules/werift/lib/ice/src/ice.js:516:21)

```

**Comment by shinyoshiaki** [comment]
Show me `/Users/me/Source/webrtctest/node_modules/werift/package.json`

**Comment by potmat** [comment]
Hi @shinyoshiaki , my mistake it does fix the "sctpMap" problem but not the invalid port problem:
```

{
  "name": "werift",
  "version": "0.14.1-debug",
  "description": "WebRTC Implementation for TypeScript (Node.js)",
  "keywords": [
    "WebRTC",
    "node.js"
  ],
  "homepage": "https://github.com/shinyoshiaki/werift-webrtc",
  "repository": {
    "type": "git",
    "url": "https://github.com/shinyoshiaki/werift-webrtc.git"
  },
  "license": "MIT",
  "author": {
    "name": "shinyoshiaki"
  },
  "main": "lib/webrtc/src/index.js",
  "types": "lib/webrtc/src/index.d.ts",
  "files": [
    "lib",
    "src"
  ],
  "scripts": {
    "build": "rm -rf lib && yarn format && tsc -p ./tsconfig.production.json",
    "depcheck": "npx depcheck --ignores='@typescript-eslint/*,eslint-*'",
    "doc": "rm -rf doc && typedoc --out doc ./src/index.ts",
    "format": "yarn unused && yarn lint && prettier --write src/**/*.ts",
    "lint": "eslint ./src --fix",
    "publish:tag": "yarn publish --tag maintain-dtls",
    "test": "npm run type && jest --runInBand --forceExit --coverage",
    "type": "tsc --noEmit --project ./tsconfig.json",
    "unused": "organize-imports-cli src/**/*.ts"
  },
  "dependencies": {
    "@fidm/x509": "^1.2.1",
    "@minhducsun2002/leb128": "^0.2.0",
    "@peculiar/webcrypto": "^1.1.6",
    "@peculiar/x509": "^1.2.2",
    "@shinyoshiaki/ebml-builder": "^0.0.1",
    "aes-js": "^3.1.2",
    "big-integer": "^1.6.49",
    "binary-data": "^0.6.0",
    "buffer-crc32": "^0.2.13",
    "date-fns": "^2.24.0",
    "debug": "^4.3.1",
    "elliptic": "^6.5.3",
    "int64-buffer": "^1.0.1",
    "ip": "^1.1.5",
    "jspack": "^0.0.4",
    "lodash": "^4.17.20",
    "nano-time": "^1.0.0",
    "p-cancelable": "^2.1.1",
    "rx.mini": "^1.1.0",
    "turbo-crc32": "^1.0.1",
    "tweetnacl": "^1.0.3",
    "uuid": "^8.3.2"
  },
  "devDependencies": {
    "@types/aes-js": "^3.1.1",
    "@types/big-integer": "^0.0.31",
    "@types/buffer-crc32": "^0.2.0",
    "@types/debug": "^4.1.7",
    "@types/elliptic": "^6.4.12",
    "@types/ip": "^1.1.0",
    "@types/jest": "^27.0.2",
    "@types/lodash": "^4.14.175",
    "@types/node": "^16.10.2",
    "@types/uuid": "^8.3.0",
    "@typescript-eslint/eslint-plugin": "^4.32.0",
    "@typescript-eslint/parser": "^4.32.0",
    "eslint-plugin-prettier": "^4.0.0",
    "jest": "^27.2.4",
    "node-actionlint": "^1.2.0",
    "prettier": "^2.4.1",
    "ts-jest": "^27.0.5",
    "ts-node": "^10.2.1",
    "typedoc": "^0.22.4",
    "typescript": "^4.4.3"
  },
  "engines": {
    "node": ">=15"
  },
  "readme": "README.md"
}

```

**Comment by potmat** [comment]
Hi @shinyoshiaki,  I don't know what my version of npm was doing but after deleting node_modules several times, clearing cache, modifying package.json several times etc. it seems I finally got it working.

Both issues seem to be resolved.  Thank you so much, apologies again for my NPM inexperience.

**Comment by potmat** [comment]
Sigh... just tried again and still getting "invalid remote port".  Seems to be intermittent at this stage?  Here is the offer and answer:

```
v=0
o=- 16650174 0 IN IP4 0.0.0.0
s=-
t=0 0
a=group:BUNDLE 0 1 2
a=extmap-allow-mixed
a=msid-semantic:WMS *
m=audio 9 UDP/TLS/RTP/SAVPF 96
c=IN IP4 0.0.0.0
a=ice-ufrag:306e
a=ice-pwd:67adf4660466c9cc2a184b
a=ice-options:trickle
a=fingerprint:sha-256 0D:B9:17:B4:8B:9B:16:76:88:49:B9:09:17:52:5E:90:C5:A4:8C:30:32:CA:52:06:EA:74:63:B7:BD:38:F0:E6
a=setup:actpass
a=recvonly
a=mid:0
a=msid:40f254fd-0cf9-44c1-9564-624fec0f1a32 f7849d66-2fd6-4a89-8940-d55daec8a1fb
a=rtcp:9 IN IP4 0.0.0.0
a=rtcp-mux
a=ssrc:3869751840 cname:7e49eaa7-6ebc-43a5-870f-de29c0205c2f
a=rtpmap:96 opus/48000/2
m=video 9 UDP/TLS/RTP/SAVPF 97
c=IN IP4 0.0.0.0
a=ice-ufrag:306e
a=ice-pwd:67adf4660466c9cc2a184b
a=ice-options:trickle
a=fingerprint:sha-256 0D:B9:17:B4:8B:9B:16:76:88:49:B9:09:17:52:5E:90:C5:A4:8C:30:32:CA:52:06:EA:74:63:B7:BD:38:F0:E6
a=setup:actpass
a=recvonly
a=mid:1
a=msid:1c275ad5-3f47-47a5-9446-f6349543fd9d 36f27ce6-5231-4c20-b5a3-ed01c1265c65
a=rtcp:9 IN IP4 0.0.0.0
a=rtcp-mux
a=ssrc:2237260815 cname:7e49eaa7-6ebc-43a5-870f-de29c0205c2f
a=rtpmap:97 VP9/90000
a=rtcp-fb:97 ccm fir
a=rtcp-fb:97 nack
a=rtcp-fb:97 nack pli
a=rtcp-fb:97 goog-remb
m=application 9 UDP/DTLS/SCTP webrtc-datachannel
c=IN IP4 0.0.0.0
a=ice-ufrag:306e
a=ice-pwd:67adf4660466c9cc2a184b
a=ice-options:trickle
a=fingerprint:sha-256 0D:B9:17:B4:8B:9B:16:76:88:49:B9:09:17:52:5E:90:C5:A4:8C:30:32:CA:52:06:EA:74:63:B7:BD:38:F0:E6
a=setup:actpass
a=mid:2
a=sctp-port:5000
a=max-message-size:65536

```


```
v=0
o=- 0 2 IN IP4 127.0.0.1
s=-
t=0 0
a=group:BUNDLE 0 2 1
a=msid-semantic: WMS 3413901960722512344/3212739396 virtual-6666
a=ice-lite
m=audio 19305 UDP/TLS/RTP/SAVPF 96
c=IN IP4 <redacted>
a=rtcp:9 IN IP4 0.0.0.0
a=candidate: 1 udp 2113939711 2607:f8b0:400e:c0a::7f 19305 typ host generation 0
a=candidate: 1 tcp 2113939710 2607:f8b0:400e:c0a::7f 19305 typ host tcptype passive generation 0
a=candidate: 1 ssltcp 2113939709 2607:f8b0:400e:c0a::7f 443 typ host generation 0
a=candidate: 1 udp 2113932031 172.253.117.127 19305 typ host generation 0
a=candidate: 1 tcp 2113932030 172.253.117.127 19305 typ host tcptype passive generation 0
a=candidate: 1 ssltcp 2113932029 172.253.117.127 443 typ host generation 0
a=ice-ufrag:HCFZK6DU+ANI7D4D
a=ice-pwd:NZ7JZFTDWN3P8DWFW2KKWCSW
a=fingerprint:sha-256 7C:51:FF:1F:DC:19:DB:10:41:ED:3F:96:E0:DF:89:46:30:6B:CB:B2:02:E5:3E:A5:F8:BA:AC:B7:DD:C5:99:C7
a=setup:passive
a=mid:0
a=sendrecv
a=msid:virtual-6666 virtual-6666
a=rtcp-mux
a=rtpmap:96 opus/48000/2
a=fmtp:96 minptime=10;useinbandfec=1
a=ssrc:6666 cname:6666
m=video 9 UDP/TLS/RTP/SAVPF 97
c=IN IP4 0.0.0.0
a=rtcp:9 IN IP4 0.0.0.0
a=ice-ufrag:HCFZK6DU+ANI7D4D
a=ice-pwd:NZ7JZFTDWN3P8DWFW2KKWCSW
a=fingerprint:sha-256 7C:51:FF:1F:DC:19:DB:10:41:ED:3F:96:E0:DF:89:46:30:6B:CB:B2:02:E5:3E:A5:F8:BA:AC:B7:DD:C5:99:C7
a=setup:passive
a=mid:1
a=sendrecv
a=msid:3413901960722512344/3212739396 3413901960722512344/3212739396
a=rtcp-mux
a=rtpmap:97 VP9/90000
a=rtcp-fb:97 ccm fir
a=rtcp-fb:97 nack
a=rtcp-fb:97 nack pli
a=rtcp-fb:97 goog-remb
a=fmtp:97 profile-id=0
a=ssrc:3212739396 cname:3212739396
m=application 9 DTLS/SCTP 5000
c=IN IP4 0.0.0.0
a=ice-ufrag:HCFZK6DU+ANI7D4D
a=ice-pwd:NZ7JZFTDWN3P8DWFW2KKWCSW
a=fingerprint:sha-256 7C:51:FF:1F:DC:19:DB:10:41:ED:3F:96:E0:DF:89:46:30:6B:CB:B2:02:E5:3E:A5:F8:BA:AC:B7:DD:C5:99:C7
a=setup:passive
a=mid:2
a=sctpmap:5000 webrtc-datachannel 1024
```

```
/Users/me/Source/webrtctest/node_modules/werift/lib/sctp/src/sctp.js:888
            throw new Error("invalid remote port");
                  ^

Error: invalid remote port
    at SCTP.sendChunk (/Users/me/Source/webrtctest/node_modules/werift/lib/sctp/src/sctp.js:888:19)
    at SCTP.receiveChunk (/Users/me/Source/webrtctest/node_modules/werift/lib/sctp/src/sctp.js:290:32)
    at SCTP.handleData (/Users/me/Source/webrtctest/node_modules/werift/lib/sctp/src/sctp.js:231:24)
    at RTCDtlsTransport.SCTP.transport.onData [as dataReceiver] (/Users/me/Source/webrtctest/node_modules/werift/lib/sctp/src/sctp.js:196:18)
    at Object.execute (/Users/me/Source/webrtctest/node_modules/werift/lib/webrtc/src/transport/dtls.js:89:22)
    at Event.execute (/Users/me/Source/webrtctest/node_modules/rx.mini/lib/core/index.js:17:30)
    at IceTransport.DtlsSocket.udpOnMessage [as onData] (/Users/me/Source/webrtctest/node_modules/werift/lib/dtls/src/socket.js:70:45)
    at Object.execute (/Users/me/Source/webrtctest/node_modules/werift/lib/webrtc/src/transport/dtls.js:221:26)
    at Event.execute (/Users/me/Source/webrtctest/node_modules/rx.mini/lib/core/index.js:17:30)
    at Connection.dataReceived (/Users/me/Source/webrtctest/node_modules/werift/lib/ice/src/ice.js:522:21)
```

**Comment by potmat** [comment]
Here's an offer and answer that worked:
```
v=0
o=- 15465665 0 IN IP4 0.0.0.0
s=-
t=0 0
a=group:BUNDLE 0 1 2
a=extmap-allow-mixed
a=msid-semantic:WMS *
m=audio 9 UDP/TLS/RTP/SAVPF 96
c=IN IP4 0.0.0.0
a=ice-ufrag:7eda
a=ice-pwd:f842afa99eba6e9e49901a
a=ice-options:trickle
a=fingerprint:sha-256 C0:AA:BC:A1:D6:E7:E6:57:7D:5A:53:3A:FD:10:22:5D:5C:54:5A:16:2C:34:E3:A4:A2:87:A2:FC:F4:AF:09:58
a=setup:actpass
a=recvonly
a=mid:0
a=msid:d72f9e29-5a95-41a8-8764-24864426c4dd 59605e05-56c2-4d1b-b390-3e9d1c4bf47d
a=rtcp:9 IN IP4 0.0.0.0
a=rtcp-mux
a=ssrc:492892577 cname:9f40fa11-19fc-4cbc-83ff-9c9e338838ed
a=rtpmap:96 opus/48000/2
m=video 9 UDP/TLS/RTP/SAVPF 97
c=IN IP4 0.0.0.0
a=ice-ufrag:7eda
a=ice-pwd:f842afa99eba6e9e49901a
a=ice-options:trickle
a=fingerprint:sha-256 C0:AA:BC:A1:D6:E7:E6:57:7D:5A:53:3A:FD:10:22:5D:5C:54:5A:16:2C:34:E3:A4:A2:87:A2:FC:F4:AF:09:58
a=setup:actpass
a=recvonly
a=mid:1
a=msid:25b73949-ae71-41b2-ba5c-a50c862fa710 502b7cee-dcd4-4042-a144-79e35368f1bc
a=rtcp:9 IN IP4 0.0.0.0
a=rtcp-mux
a=ssrc:4049543087 cname:9f40fa11-19fc-4cbc-83ff-9c9e338838ed
a=rtpmap:97 VP9/90000
a=rtcp-fb:97 ccm fir
a=rtcp-fb:97 nack
a=rtcp-fb:97 nack pli
a=rtcp-fb:97 goog-remb
m=application 9 UDP/DTLS/SCTP webrtc-datachannel
c=IN IP4 0.0.0.0
a=ice-ufrag:7eda
a=ice-pwd:f842afa99eba6e9e49901a
a=ice-options:trickle
a=fingerprint:sha-256 C0:AA:BC:A1:D6:E7:E6:57:7D:5A:53:3A:FD:10:22:5D:5C:54:5A:16:2C:34:E3:A4:A2:87:A2:FC:F4:AF:09:58
a=setup:actpass
a=mid:2
a=sctp-port:5000
a=max-message-size:65536
```

```
v=0
o=- 0 2 IN IP4 127.0.0.1
s=-
t=0 0
a=group:BUNDLE 0 2 1
a=msid-semantic: WMS 15700875492317516519/3212739396 virtual-6666
a=ice-lite
m=audio 19305 UDP/TLS/RTP/SAVPF 96
c=IN IP4 <redacted>
a=rtcp:9 IN IP4 0.0.0.0
a=candidate: 1 udp 2113939711 2607:f8b0:400e:c0a::7f 19305 typ host generation 0
a=candidate: 1 tcp 2113939710 2607:f8b0:400e:c0a::7f 19305 typ host tcptype passive generation 0
a=candidate: 1 ssltcp 2113939709 2607:f8b0:400e:c0a::7f 443 typ host generation 0
a=candidate: 1 udp 2113932031 172.253.117.127 19305 typ host generation 0
a=candidate: 1 tcp 2113932030 172.253.117.127 19305 typ host tcptype passive generation 0
a=candidate: 1 ssltcp 2113932029 172.253.117.127 443 typ host generation 0
a=ice-ufrag:2IAVVLLEMWRAUBF/
a=ice-pwd:KSDTPK4ZVCUMAUCRCAU2AXOO
a=fingerprint:sha-256 0C:AE:92:28:ED:43:7B:A0:A5:1C:4A:8D:6E:F7:F3:62:C8:A9:37:1D:D4:2D:31:8C:96:9F:01:47:9D:AF:05:1C
a=setup:passive
a=mid:0
a=sendrecv
a=msid:virtual-6666 virtual-6666
a=rtcp-mux
a=rtpmap:96 opus/48000/2
a=fmtp:96 minptime=10;useinbandfec=1
a=ssrc:6666 cname:6666
m=video 9 UDP/TLS/RTP/SAVPF 97
c=IN IP4 0.0.0.0
a=rtcp:9 IN IP4 0.0.0.0
a=ice-ufrag:2IAVVLLEMWRAUBF/
a=ice-pwd:KSDTPK4ZVCUMAUCRCAU2AXOO
a=fingerprint:sha-256 0C:AE:92:28:ED:43:7B:A0:A5:1C:4A:8D:6E:F7:F3:62:C8:A9:37:1D:D4:2D:31:8C:96:9F:01:47:9D:AF:05:1C
a=setup:passive
a=mid:1
a=sendrecv
a=msid:15700875492317516519/3212739396 15700875492317516519/3212739396
a=rtcp-mux
a=rtpmap:97 VP9/90000
a=rtcp-fb:97 ccm fir
a=rtcp-fb:97 nack
a=rtcp-fb:97 nack pli
a=rtcp-fb:97 goog-remb
a=fmtp:97 profile-id=0
a=ssrc:3212739396 cname:3212739396
m=application 9 DTLS/SCTP 5000
c=IN IP4 0.0.0.0
a=ice-ufrag:2IAVVLLEMWRAUBF/
a=ice-pwd:KSDTPK4ZVCUMAUCRCAU2AXOO
a=fingerprint:sha-256 0C:AE:92:28:ED:43:7B:A0:A5:1C:4A:8D:6E:F7:F3:62:C8:A9:37:1D:D4:2D:31:8C:96:9F:01:47:9D:AF:05:1C
a=setup:passive
a=mid:2
a=sctpmap:5000 webrtc-datachannel 1024
```

**Comment by shinyoshiaki** [comment]
Please try this version.
`0.14.2-debug0`

**Comment by potmat** [comment]
Offer:

```
v=0
o=- 18095310 0 IN IP4 0.0.0.0
s=-
t=0 0
a=group:BUNDLE 0 1 2
a=extmap-allow-mixed
a=msid-semantic:WMS *
m=audio 9 UDP/TLS/RTP/SAVPF 96
c=IN IP4 0.0.0.0
a=ice-ufrag:becf
a=ice-pwd:39ee1842e742b34f2793d7
a=ice-options:trickle
a=fingerprint:sha-256 6C:FB:8B:F6:CF:D0:55:54:B6:84:24:1C:96:38:4F:B9:30:5F:08:AB:FF:CF:02:BA:98:25:8E:1D:A8:D3:AC:50
a=setup:actpass
a=recvonly
a=mid:0
a=msid:dc28cef1-7a3a-46e5-9451-b36ef33e47aa 2f32df69-e7d9-4cdf-8c12-0afa53018db9
a=rtcp:9 IN IP4 0.0.0.0
a=rtcp-mux
a=ssrc:2652799432 cname:31b13d4e-4f12-4936-9185-cae933a4a27b
a=rtpmap:96 opus/48000/2
m=video 9 UDP/TLS/RTP/SAVPF 97
c=IN IP4 0.0.0.0
a=ice-ufrag:becf
a=ice-pwd:39ee1842e742b34f2793d7
a=ice-options:trickle
a=fingerprint:sha-256 6C:FB:8B:F6:CF:D0:55:54:B6:84:24:1C:96:38:4F:B9:30:5F:08:AB:FF:CF:02:BA:98:25:8E:1D:A8:D3:AC:50
a=setup:actpass
a=recvonly
a=mid:1
a=msid:a0259bad-164d-4e74-88e6-02f9626aaecc 6848b824-71e5-4872-bf85-50c21c0d8ac2
a=rtcp:9 IN IP4 0.0.0.0
a=rtcp-mux
a=ssrc:3645065385 cname:31b13d4e-4f12-4936-9185-cae933a4a27b
a=rtpmap:97 VP8/90000
a=rtcp-fb:97 ccm fir
a=rtcp-fb:97 nack
a=rtcp-fb:97 nack pli
a=rtcp-fb:97 goog-remb
m=application 9 UDP/DTLS/SCTP webrtc-datachannel
c=IN IP4 0.0.0.0
a=ice-ufrag:becf
a=ice-pwd:39ee1842e742b34f2793d7
a=ice-options:trickle
a=fingerprint:sha-256 6C:FB:8B:F6:CF:D0:55:54:B6:84:24:1C:96:38:4F:B9:30:5F:08:AB:FF:CF:02:BA:98:25:8E:1D:A8:D3:AC:50
a=setup:actpass
a=mid:2
a=sctp-port:5000
a=max-message-size:65536
```

Answer:

```
v=0
o=- 0 2 IN IP4 127.0.0.1
s=-
t=0 0
a=group:BUNDLE 0 2 1
a=msid-semantic: WMS 18214946987340425118/3212739396 virtual-6666
a=ice-lite
m=audio 19305 UDP/TLS/RTP/SAVPF 96
c=IN IP4 172.253.117.127
a=rtcp:9 IN IP4 0.0.0.0
a=candidate: 1 udp 2113939711 2607:f8b0:400e:c0a::7f 19305 typ host generation 0
a=candidate: 1 tcp 2113939710 2607:f8b0:400e:c0a::7f 19305 typ host tcptype passive generation 0
a=candidate: 1 ssltcp 2113939709 2607:f8b0:400e:c0a::7f 443 typ host generation 0
a=candidate: 1 udp 2113932031 172.253.117.127 19305 typ host generation 0
a=candidate: 1 tcp 2113932030 172.253.117.127 19305 typ host tcptype passive generation 0
a=candidate: 1 ssltcp 2113932029 172.253.117.127 443 typ host generation 0
a=ice-ufrag:GV9TG0PZQJGL9HGJ
a=ice-pwd:I5QLLU0HH9YNYVIBIJAVHOHO
a=fingerprint:sha-256 BF:AB:24:5E:D7:58:35:C9:2E:54:63:9D:68:7D:A9:C9:12:FB:61:4B:CA:4D:DA:C4:B5:7F:60:7B:B6:71:B7:61
a=setup:passive
a=mid:0
a=sendrecv
a=msid:virtual-6666 virtual-6666
a=rtcp-mux
a=rtpmap:96 opus/48000/2
a=fmtp:96 minptime=10;useinbandfec=1
a=ssrc:6666 cname:6666
m=video 9 UDP/TLS/RTP/SAVPF 97
c=IN IP4 0.0.0.0
a=rtcp:9 IN IP4 0.0.0.0
a=ice-ufrag:GV9TG0PZQJGL9HGJ
a=ice-pwd:I5QLLU0HH9YNYVIBIJAVHOHO
a=fingerprint:sha-256 BF:AB:24:5E:D7:58:35:C9:2E:54:63:9D:68:7D:A9:C9:12:FB:61:4B:CA:4D:DA:C4:B5:7F:60:7B:B6:71:B7:61
a=setup:passive
a=mid:1
a=sendrecv
a=msid:18214946987340425118/3212739396 18214946987340425118/3212739396
a=rtcp-mux
a=rtpmap:97 VP8/90000
a=rtcp-fb:97 ccm fir
a=rtcp-fb:97 nack
a=rtcp-fb:97 nack pli
a=rtcp-fb:97 goog-remb
a=ssrc:3212739396 cname:3212739396
m=application 9 DTLS/SCTP 5000
c=IN IP4 0.0.0.0
a=ice-ufrag:GV9TG0PZQJGL9HGJ
a=ice-pwd:I5QLLU0HH9YNYVIBIJAVHOHO
a=fingerprint:sha-256 BF:AB:24:5E:D7:58:35:C9:2E:54:63:9D:68:7D:A9:C9:12:FB:61:4B:CA:4D:DA:C4:B5:7F:60:7B:B6:71:B7:61
a=setup:passive
a=mid:2
a=sctpmap:5000 webrtc-datachannel 1024
```

Result:

```
/Users/me/Source/webrtctest/node_modules/werift/lib/sctp/src/sctp.js:890
            throw new Error("invalid remote port");
                  ^

Error: invalid remote port
    at SCTP.sendChunk (/Users/me/Source/webrtctest/node_modules/werift/lib/sctp/src/sctp.js:890:19)
    at SCTP.receiveChunk (/Users/me/Source/webrtctest/node_modules/werift/lib/sctp/src/sctp.js:290:32)
    at SCTP.handleData (/Users/me/Source/webrtctest/node_modules/werift/lib/sctp/src/sctp.js:231:24)
    at RTCDtlsTransport.SCTP.transport.onData [as dataReceiver] (/Users/me/Source/webrtctest/node_modules/werift/lib/sctp/src/sctp.js:196:18)
    at Object.execute (/Users/me/Source/webrtctest/node_modules/werift/lib/webrtc/src/transport/dtls.js:89:22)
    at Event.execute (/Users/me/Source/webrtctest/node_modules/rx.mini/lib/core/index.js:17:30)
    at IceTransport.DtlsSocket.udpOnMessage [as onData] (/Users/me/Source/webrtctest/node_modules/werift/lib/dtls/src/socket.js:70:45)
    at Object.execute (/Users/me/Source/webrtctest/node_modules/werift/lib/webrtc/src/transport/dtls.js:221:26)
    at Event.execute (/Users/me/Source/webrtctest/node_modules/rx.mini/lib/core/index.js:17:30)
    at Connection.dataReceived (/Users/me/Source/webrtctest/node_modules/werift/lib/ice/src/ice.js:522:21)
```

**Comment by shinyoshiaki** [comment]
Sorry. I had deploy without build.
try this version
`0.14.2-debug1`

**Comment by potmat** [comment]
Offer:

```
v=0
o=- 11288766 0 IN IP4 0.0.0.0
s=-
t=0 0
a=group:BUNDLE 0 1 2
a=extmap-allow-mixed
a=msid-semantic:WMS *
m=audio 9 UDP/TLS/RTP/SAVPF 96
c=IN IP4 0.0.0.0
a=ice-ufrag:c08d
a=ice-pwd:26f23267a504ac50e92821
a=ice-options:trickle
a=fingerprint:sha-256 B7:6B:31:4E:DA:CC:DA:8F:49:9F:CE:58:66:FD:B3:58:7D:A3:4B:C0:47:B2:EB:D8:73:70:79:40:5A:85:3A:7B
a=setup:actpass
a=recvonly
a=mid:0
a=msid:2aeb4bb6-fdb3-4ace-ab42-398c41dc1f53 91b9dbea-ef37-4184-91e9-9ad0231d0aea
a=rtcp:9 IN IP4 0.0.0.0
a=rtcp-mux
a=ssrc:819886237 cname:080089b7-625d-496d-99d9-ed40e55d843b
a=rtpmap:96 opus/48000/2
m=video 9 UDP/TLS/RTP/SAVPF 97 98
c=IN IP4 0.0.0.0
a=ice-ufrag:c08d
a=ice-pwd:26f23267a504ac50e92821
a=ice-options:trickle
a=fingerprint:sha-256 B7:6B:31:4E:DA:CC:DA:8F:49:9F:CE:58:66:FD:B3:58:7D:A3:4B:C0:47:B2:EB:D8:73:70:79:40:5A:85:3A:7B
a=setup:actpass
a=recvonly
a=mid:1
a=msid:d839e0d9-e606-4d49-aa5f-1e5a748e54d8 b91cd35a-eac5-4ffe-b0c3-75f73da84ae6
a=rtcp:9 IN IP4 0.0.0.0
a=rtcp-mux
a=ssrc:2393625669 cname:080089b7-625d-496d-99d9-ed40e55d843b
a=rtpmap:97 VP9/90000
a=rtcp-fb:97 ccm fir
a=rtcp-fb:97 nack
a=rtcp-fb:97 nack pli
a=rtcp-fb:97 goog-remb
a=rtpmap:98 VP8/90000
a=rtcp-fb:98 ccm fir
a=rtcp-fb:98 nack
a=rtcp-fb:98 nack pli
a=rtcp-fb:98 goog-remb
m=application 9 UDP/DTLS/SCTP webrtc-datachannel
c=IN IP4 0.0.0.0
a=ice-ufrag:c08d
a=ice-pwd:26f23267a504ac50e92821
a=ice-options:trickle
a=fingerprint:sha-256 B7:6B:31:4E:DA:CC:DA:8F:49:9F:CE:58:66:FD:B3:58:7D:A3:4B:C0:47:B2:EB:D8:73:70:79:40:5A:85:3A:7B
a=setup:actpass
a=mid:2
a=sctp-port:5000
a=max-message-size:65536
```

Answer:

```
v=0
o=- 0 2 IN IP4 127.0.0.1
s=-
t=0 0
a=group:BUNDLE 0 2 1
a=msid-semantic: WMS 14158722289406540344/3212739396 virtual-6666
a=ice-lite
m=audio 19305 UDP/TLS/RTP/SAVPF 96
c=IN IP4 <redacted>
a=rtcp:9 IN IP4 0.0.0.0
a=candidate: 1 udp 2113939711 2607:f8b0:400e:c0a::7f 19305 typ host generation 0
a=candidate: 1 tcp 2113939710 2607:f8b0:400e:c0a::7f 19305 typ host tcptype passive generation 0
a=candidate: 1 ssltcp 2113939709 2607:f8b0:400e:c0a::7f 443 typ host generation 0
a=candidate: 1 udp 2113932031 172.253.117.127 19305 typ host generation 0
a=candidate: 1 tcp 2113932030 172.253.117.127 19305 typ host tcptype passive generation 0
a=candidate: 1 ssltcp 2113932029 172.253.117.127 443 typ host generation 0
a=ice-ufrag:ZBRRX/SQN8VU9ZU7
a=ice-pwd:EQZV+LRUAQDXCKZKE6IOZNDP
a=fingerprint:sha-256 D3:03:83:36:BC:0F:BD:78:E1:97:8D:7E:74:E2:BF:E5:83:9B:67:B1:83:92:68:2F:08:BB:3C:4D:E9:D5:30:01
a=setup:passive
a=mid:0
a=sendrecv
a=msid:virtual-6666 virtual-6666
a=rtcp-mux
a=rtpmap:96 opus/48000/2
a=fmtp:96 minptime=10;useinbandfec=1
a=ssrc:6666 cname:6666
m=video 9 UDP/TLS/RTP/SAVPF 97 98
c=IN IP4 0.0.0.0
a=rtcp:9 IN IP4 0.0.0.0
a=ice-ufrag:ZBRRX/SQN8VU9ZU7
a=ice-pwd:EQZV+LRUAQDXCKZKE6IOZNDP
a=fingerprint:sha-256 D3:03:83:36:BC:0F:BD:78:E1:97:8D:7E:74:E2:BF:E5:83:9B:67:B1:83:92:68:2F:08:BB:3C:4D:E9:D5:30:01
a=setup:passive
a=mid:1
a=sendrecv
a=msid:14158722289406540344/3212739396 14158722289406540344/3212739396
a=rtcp-mux
a=rtpmap:97 VP9/90000
a=rtcp-fb:97 ccm fir
a=rtcp-fb:97 nack
a=rtcp-fb:97 nack pli
a=rtcp-fb:97 goog-remb
a=fmtp:97 profile-id=0
a=rtpmap:98 VP8/90000
a=rtcp-fb:98 ccm fir
a=rtcp-fb:98 nack
a=rtcp-fb:98 nack pli
a=rtcp-fb:98 goog-remb
a=ssrc:3212739396 cname:3212739396
m=application 9 DTLS/SCTP 5000
c=IN IP4 0.0.0.0
a=ice-ufrag:ZBRRX/SQN8VU9ZU7
a=ice-pwd:EQZV+LRUAQDXCKZKE6IOZNDP
a=fingerprint:sha-256 D3:03:83:36:BC:0F:BD:78:E1:97:8D:7E:74:E2:BF:E5:83:9B:67:B1:83:92:68:2F:08:BB:3C:4D:E9:D5:30:01
a=setup:passive
a=mid:2
a=sctpmap:5000 webrtc-datachannel 1024
```

Result:

```
Error: invalid remote port
    at SCTP.sendChunk (/Users/me/Source/webrtctest/node_modules/werift/lib/sctp/src/sctp.js:890:19)
    at SCTP.receiveChunk (/Users/me/Source/webrtctest/node_modules/werift/lib/sctp/src/sctp.js:290:32)
    at SCTP.handleData (/Users/me/Source/webrtctest/node_modules/werift/lib/sctp/src/sctp.js:231:24)
    at RTCDtlsTransport.SCTP.transport.onData [as dataReceiver] (/Users/me/Source/webrtctest/node_modules/werift/lib/sctp/src/sctp.js:196:18)
    at Object.execute (/Users/me/Source/webrtctest/node_modules/werift/lib/webrtc/src/transport/dtls.js:89:22)
    at Event.execute (/Users/me/Source/webrtctest/node_modules/rx.mini/lib/core/index.js:17:30)
    at IceTransport.DtlsSocket.udpOnMessage [as onData] (/Users/me/Source/webrtctest/node_modules/werift/lib/dtls/src/socket.js:70:45)
    at Object.execute (/Users/me/Source/webrtctest/node_modules/werift/lib/webrtc/src/transport/dtls.js:221:26)
    at Event.execute (/Users/me/Source/webrtctest/node_modules/rx.mini/lib/core/index.js:17:30)
    at Connection.dataReceived (/Users/me/Source/webrtctest/node_modules/werift/lib/ice/src/ice.js:522:21)
```

**Comment by shinyoshiaki** [comment]
Try use the following A and B
`0.14.2-debug2a`
`0.14.2-debug2b`

**Comment by potmat** [comment]
Hi @shinyoshiaki, thank you for your hard work on this.  Both branches seem to work fine!
